sudo: required
dist: trusty
language: c

services:
  - docker

addons:
  apt:
    sources:
    - sourceline: deb https://download.docker.com/linux/ubuntu trusty stable
      key_url: https://download.docker.com/linux/ubuntu/gpg
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - docker-ce

before_install:
  - if [ $TRAVIS_PULL_REQUEST == "false" ]; then docker login -u $DOCKER_USER -p $DOCKER_PASSWORD; fi
script:
  - docker build -t tanibox/php7-fpm -f php-fpm/Dockerfile .
  - docker build -t tanibox/php7-fpm-nginx-supervisord -f php-fpm-nginx-supervisord/Dockerfile .
  - docker tag tanibox/php7-fpm:latest tanibox/php7-fpm:travis-$TRAVIS_BUILD_NUMBER
  - docker tag tanibox/php7-fpm-nginx-supervisord tanibox/php7-fpm-nginx-supervisord:travis-$TRAVIS_BUILD_NUMBER
after_success:
  - |
    set -e 
    if [ $TRAVIS_PULL_REQUEST == "false" ]
    then 
      docker push tanibox/php7-fpm
      docker push tanibox/php7-fpm-nginx-supervisord
      docker push tanibox/php7-fpm:travis-$TRAVIS_BUILD_NUMBER
      docker push tanibox/php7-fpm-nginx-supervisord:travis-$TRAVIS_BUILD_NUMBER
    fi 
env:
  global:
  - secure: g0ywdrBBhCtpMPTjSf/D5DhuiXaMUYGWKfmReQ5OK6RIWBpIPmJpyhbl5ZAvVPMzx354MuqeWGYpGr39KGlEQ5Jes5ijOBjPvpqs1P48uDIVbMyfYCaIphGdVn4e65HpX2Y8LxwmoLwdRrx9pMDVqd+snSOuWg7AELHpjrDwRMEPbLlaF1kpFjJfdC2dh49H0j8psfn1TLtpL+QqYE+5OFhiwgZZZDKG8wOXx3hl0GPP7cpmRKBGkl124+Jndz7LraUt4MUNNin+QHOuwBvOAKtn4bvDEGTrTjLYtrnWAsldErUBMiLK0g6DOoSUUxtfIYeVyNVQSQYz3Fc3debyUX1FoAU/sG2yaXI81aiL0xsIRPTmtnpw2PAm2luC6/gqt8zKiI63nRdWawwZTeo6P45hJaSEvWKY3wiy6rndZcHZvFKIvSyiBX+guXhbscv4Ufa1QDuKYU60IPPvfCr9jxIXo19boNydF9ztsvO2moRPZzZE9Y+LJEavJBJ6GrYpsP9L69rMK2l5ySYyRi1WzyyfRldH9eUkUPfitwlAJc3j9/TKECorpMbQ1GZJ+r+xsyYCMw6fi5MzKbHlrG4DHTVBYn6PX6iMvKItnC1HYagG/UMVMQ0nX2vc8OQNjRNvqIH6SjGZKfpiMH83xxF4eS/R6qZ/p/hZO50bC1zdbiQ=
  - secure: 2WVjGK9Jk3mREyEnudg50ghXD/Gjh/s4cDvEQpX7GR5GTqOXLlh+Bf/RIKKn/q/iFcT/zFYwla4x4rGxCa0yYaAWsjAIqiuXeuO23kyAjWh1bKdCfrHlurxXunPgsjQw07RFP2Wk723VdjkiuUPRiPByYtynCwwNnu4jSCBa7BdkuMP61v/vfriIyRNxXSk9JZmgvorIx40T35J7X5rAWGRdVRp8tTZPU2CGqg7Pl63hlDeJOk5iX0m7wu2gUDLoaLBWOLUh6XSQM36kzE31Pl6qj35iNfg+rx2FIXyV+CxGWSF+E+s2gmwVMX05F058cFB5DzppOTJjIaFrKF9P6PgaZOwMCfC+zvATQdjOUqvRkQMfpTXxdvs01MvFLob5N5dV7WTIMRW4ZXUHR8ihsieaVDhmFwaeCDvjywmhgxb3wktxSGfnVt7yWq7ZF58SOAFtdHsZkoTNpmqoGDYbIHzGKNFFRqaHe7HQ4LKFreWzX3Z6+ZF5XGuGyfM8Y/SfSfMpWzHUBWwcgM+siWdwQ2rAdc1m5v3qYoe9Lh7BhbnQN5CK6y6neM3zY2BUE0DtkMyRdwpklAMsfu1Ht2dor1L3UAc0N54v1XiA4nrtV12xl6EPsv7cOdHXv4KoiTFvargIvh9gqXl6sQwZ3p4jC0qtrknyncNQRLX+xIAw9gs=
